Welcome to Extrae 3.1.0 (revision 3316 based on extrae/trunk)
Extrae: Parsing the configuration file (../extrae.xml) begins
Extrae: Tracing package is located on /scratch/package
Extrae: Generating intermediate files for Paraver traces.
Extrae: Tracing buffer can hold 500000 events
Extrae: Circular buffer disabled.
Extrae: Dynamic memory instrumentation is disabled.
Extrae: Basic I/O memory instrumentation is disabled.
Extrae: Parsing the configuration file (../extrae.xml) has ended
Extrae: Intermediate traces will be stored in /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_nothing
Extrae: Tracing mode is set to: Detail.
Extrae: Successfully initiated with 1 tasks

starting program
Warning: not specified file with names of the tasks: use export TASKNAMES=<path>
The names of the tasks may be corrupted!!!!
Testing: emit css start 
Testing: starting task with name fake_name
Testing: find_taskcode NOT YET SPECIFIED,  fake_name  -->  1
Testing: starting task number 1  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 1
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 1
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 2  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 2
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 2
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 3  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 3
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 3
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 4  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 4
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 4
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 5  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 5
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 5
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 6  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 6
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 6
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 7  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 7
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 7
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 8  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 8
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 8
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 9  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 9
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 9
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 10  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 10
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 10
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 11  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 11
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 11
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 12  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 12
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 12
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 13  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 13
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 13
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 14  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 14
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 14
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 15  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 15
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 15
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 16  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 16
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 16
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 17  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 17
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 17
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 18  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 18
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 18
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 19  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 19
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 19
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 20  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 20
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 20
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 21  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 21
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 21
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 22  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 22
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 22
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 23  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 23
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 23
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 24  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 24
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 24
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 25  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 25
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 25
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 26  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 26
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 26
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 27  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 27
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 27
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 28  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 28
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 28
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 29  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 29
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 29
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 30  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 30
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 30
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 31  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 31
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 31
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 32  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 32
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 32
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 33  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 33
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 33
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 34  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 34
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 34
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 35  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 35
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 35
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 36  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 36
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 36
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 37  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 37
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 37
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 38  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 38
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 38
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 39  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 39
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 39
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 40  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 40
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 40
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 41  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 41
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 41
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 42  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 42
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 42
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 43  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 43
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 43
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 44  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 44
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 44
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 45  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 45
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 45
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 46  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 46
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 46
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 47  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 47
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 47
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 48  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 48
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 48
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 49  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 49
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 49
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 50  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 50
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 50
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 51  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 51
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 51
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 52  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 52
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 52
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 53  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 53
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 53
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 54  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 54
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 54
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 55  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 55
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 55
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 56  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 56
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 56
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 57  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 57
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 57
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 58  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 58
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 58
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 59  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 59
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 59
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 60  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 60
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 60
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 61  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 61
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 61
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 62  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 62
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 62
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 63  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 63
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 63
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 64  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 64
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 64
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 65  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 65
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 65
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 66  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 66
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 66
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 67  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 67
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 67
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 68  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 68
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 68
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 69  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 69
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 69
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 70  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 70
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 70
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 71  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 71
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 71
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 72  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 72
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 72
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 73  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 73
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 73
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 74  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 74
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 74
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 75  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 75
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 75
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 76  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 76
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 76
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 77  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 77
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 77
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 78  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 78
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 78
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 79  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 79
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 79
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 80  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 80
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 80
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 81  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 81
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 81
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 82  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 82
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 82
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 83  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 83
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 83
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 84  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 84
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 84
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 85  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 85
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 85
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 86  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 86
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 86
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 87  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 87
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 87
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 88  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 88
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 88
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 89  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 89
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 89
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 90  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 90
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 90
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 91  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 91
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 91
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 92  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 92
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 92
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 93  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 93
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 93
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 94  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 94
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 94
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 95  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 95
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 95
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 96  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 96
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 96
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 97  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 97
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 97
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 98  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 98
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 98
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 99  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 99
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 99
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 100  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 100
Testing: task: fake name
Done task a
Testing: ending task 
Testing: ending task number 100
Testing: emit task end
Extrae: Intermediate raw trace file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_nothing/set-0/TRACE.0000019381000000000000.mpit
Extrae: Intermediate raw sym file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_nothing/set-0/TRACE.0000019381000000000000.sym
Extrae: Deallocating memory.
Extrae: Application has ended. Tracing has been terminated.
Extrae: Proceeding with the merge of the intermediate tracefiles.
Extrae: Executing the merge process (using /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_nothing/TRACE.mpits).
merger: Extrae 3.1.0 (revision 3316 based on extrae/trunk)
mpi2prv: Assigned nodes < bsc-Latitude-E7440 >
mpi2prv: Assigned size per processor < <1 Mbyte >
mpi2prv: File /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_nothing/set-0/TRACE.0000019381000000000000.mpit is object 1.1.1 on node bsc-Latitude-E7440 assigned to processor 0
mpi2prv: Time synchronization has been turned off
mpi2prv: Checking for target directory existance... exists, ok!
mpi2prv: Ignoring symbols from the application execution because mpi2prv does not support BFD
mpi2prv: Selected output trace format is Paraver
mpi2prv: Stored trace format is Paraver
mpi2prv: Searching synchronization points... done
mpi2prv: Enabling Time Synchronization (Node).
mpi2prv: Circular buffer enabled at tracing time? NO
mpi2prv: Parsing intermediate files
mpi2prv: Progress 1 of 2 ... 7.7% 15.4% 23.1% 30.8% 38.5% 46.2% 53.8% 61.5% 69.2% 76.9% 84.6% 92.3% 100.0% done
mpi2prv: Processor 0 succeeded to translate its assigned files
mpi2prv: Elapsed time translating files: 0 hours 0 minutes 0 seconds
mpi2prv: Elapsed time sorting addresses: 0 hours 0 minutes 0 seconds
mpi2prv: Generating tracefile (intermediate buffers of 6710784 events)
         This process can take a while. Please, be patient.
mpi2prv: Progress 2 of 2 ... 13.6% 18.2% 22.7% 27.3% 50.0% 54.5% 63.6% 68.2% 77.3% 81.8% 90.9% 95.5% 100.0% done
mpi2prv: Elapsed time merge step: 0 hours 0 minutes 0 seconds
mpi2prv: Resulting tracefile occupies 500 bytes
mpi2prv: Removing temporal files... done
mpi2prv: Elapsed time removing temporal files: 0 hours 0 minutes 0 seconds
mpi2prv: Congratulations! EXTRAE_Paraver_trace.prv has been generated.
