Welcome to Extrae 3.1.0 (revision 3316 based on extrae/trunk)
Extrae: Parsing the configuration file (../extrae.xml) begins
Extrae: Tracing package is located on /scratch/package
Extrae: Generating intermediate files for Paraver traces.
Extrae: Tracing buffer can hold 500000 events
Extrae: Circular buffer disabled.
Extrae: Dynamic memory instrumentation is disabled.
Extrae: Basic I/O memory instrumentation is disabled.
Extrae: Parsing the configuration file (../extrae.xml) has ended
Extrae: Intermediate traces will be stored in /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in_out1
Extrae: Tracing mode is set to: Detail.
Extrae: Successfully initiated with 1 tasks

starting program
Warning: not specified file with names of the tasks: use export TASKNAMES=<path>
The names of the tasks may be corrupted!!!!
Testing: emit css start 
Testing: starting task with name: 6
Testing: find_taskcode NOT YET SPECIFIED,  6  -->  1
Testing: starting task number 1  name is 6 which is coded into 1 
Testing: emit task start code 1, number 1
Testing: replay_output_task parName 6    ptr ,  element_size 4,   elements  1      
Testing: replay_output_task parName 6    ptr ,  element_size 4,   elements  1      
Testing: replay_inout_task parName 6  ptr ,  element_size 4,   elements  1      
Testing: task: 6
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 1
Testing: ending task 
Testing: ending task number 1
Testing: emit task end
Testing: starting task with name: 7
Testing: find_taskcode NOT YET SPECIFIED,  7  -->  2
Testing: starting task number 2  name is 7 which is coded into 2 
Testing: emit task start code 2, number 2
Testing: replay_inout_task parName 7  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  1  ->   2 (INOUT) 
Testing: emit dependency from the previous task no: 1
Testing: replay_inout_task parName 7  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  1  ->   2 (INOUT) 
Testing: emit dependency from the previous task no: 1
Testing: task: 7
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 2
Testing: ending task 
Testing: ending task number 2
Testing: emit task end
Testing: starting task with name: 8
Testing: find_taskcode NOT YET SPECIFIED,  8  -->  3
Testing: starting task number 3  name is 8 which is coded into 3 
Testing: emit task start code 3, number 3
Testing: replay_output_task parName 8    ptr ,  element_size 4,   elements  1      
Testing: replay_output_task parName 8    ptr ,  element_size 4,   elements  1      
Testing: replay_inout_task parName 8  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  2  ->   3 (INOUT) 
Testing: emit dependency from the previous task no: 2
Testing: replay_inout_task parName 8  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  2  ->   3 (INOUT) 
Testing: emit dependency from the previous task no: 2
Testing: task: 8
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 3
Testing: ending task 
Testing: ending task number 3
Testing: emit task end
Testing: starting task with name: 9
Testing: find_taskcode NOT YET SPECIFIED,  9  -->  4
Testing: starting task number 4  name is 9 which is coded into 4 
Testing: emit task start code 4, number 4
Testing: replay_input_task parName 9    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  3  ->   4 (INPUT) 
Testing: emit dependency from the previous task no: 3
Testing: task: 9
Testing: Testing: Testing: Testing: Testing: Testing: Done task 4
Testing: ending task 
Testing: ending task number 4
Testing: emit task end
Testing: starting task with name: 10
Testing: find_taskcode NOT YET SPECIFIED,  10  -->  5
Testing: starting task number 5  name is 10 which is coded into 5 
Testing: emit task start code 5, number 5
Testing: replay_input_task parName 10    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  3  ->   5 (INPUT) 
Testing: emit dependency from the previous task no: 3
Testing: task: 10
Testing: Testing: Testing: Testing: Testing: Testing: Done task 5
Testing: ending task 
Testing: ending task number 5
Testing: emit task end
Testing: starting task with name: 11
Testing: find_taskcode NOT YET SPECIFIED,  11  -->  6
Testing: starting task number 6  name is 11 which is coded into 6 
Testing: emit task start code 6, number 6
Testing: replay_input_task parName 11    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  3  ->   6 (INPUT) 
Testing: emit dependency from the previous task no: 3
Testing: replay_inout_task parName 11  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  3  ->   6 (INOUT) 
Testing: emit dependency from the previous task no: 3
Testing: task: 11
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 6
Testing: ending task 
Testing: ending task number 6
Testing: emit task end
Testing: starting task with name: 12
Testing: find_taskcode NOT YET SPECIFIED,  12  -->  7
Testing: starting task number 7  name is 12 which is coded into 7 
Testing: emit task start code 7, number 7
Testing: replay_output_task parName 12    ptr ,  element_size 4,   elements  1      
Testing: replay_output_task parName 12    ptr ,  element_size 4,   elements  1      
Testing: replay_inout_task parName 12  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  6  ->   7 (INOUT) 
Testing: emit dependency from the previous task no: 6
Testing: task: 12
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 1
Testing: ending task 
Testing: ending task number 7
Testing: emit task end
Testing: starting task with name: 13
Testing: find_taskcode NOT YET SPECIFIED,  13  -->  8
Testing: starting task number 8  name is 13 which is coded into 8 
Testing: emit task start code 8, number 8
Testing: replay_inout_task parName 13  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  7  ->   8 (INOUT) 
Testing: emit dependency from the previous task no: 7
Testing: replay_inout_task parName 13  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  7  ->   8 (INOUT) 
Testing: emit dependency from the previous task no: 7
Testing: task: 13
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 2
Testing: ending task 
Testing: ending task number 8
Testing: emit task end
Testing: starting task with name: 14
Testing: find_taskcode NOT YET SPECIFIED,  14  -->  9
Testing: starting task number 9  name is 14 which is coded into 9 
Testing: emit task start code 9, number 9
Testing: replay_output_task parName 14    ptr ,  element_size 4,   elements  1      
Testing: replay_output_task parName 14    ptr ,  element_size 4,   elements  1      
Testing: replay_inout_task parName 14  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  8  ->   9 (INOUT) 
Testing: emit dependency from the previous task no: 8
Testing: replay_inout_task parName 14  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  8  ->   9 (INOUT) 
Testing: emit dependency from the previous task no: 8
Testing: task: 14
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 3
Testing: ending task 
Testing: ending task number 9
Testing: emit task end
Testing: starting task with name: 15
Testing: find_taskcode NOT YET SPECIFIED,  15  -->  10
Testing: starting task number 10  name is 15 which is coded into 10 
Testing: emit task start code 10, number 10
Testing: replay_input_task parName 15    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  9  ->   10 (INPUT) 
Testing: emit dependency from the previous task no: 9
Testing: task: 15
Testing: Testing: Testing: Testing: Testing: Testing: Done task 4
Testing: ending task 
Testing: ending task number 10
Testing: emit task end
Testing: starting task with name: 16
Testing: find_taskcode NOT YET SPECIFIED,  16  -->  11
Testing: starting task number 11  name is 16 which is coded into 11 
Testing: emit task start code 11, number 11
Testing: replay_input_task parName 16    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  9  ->   11 (INPUT) 
Testing: emit dependency from the previous task no: 9
Testing: task: 16
Testing: Testing: Testing: Testing: Testing: Testing: Done task 5
Testing: ending task 
Testing: ending task number 11
Testing: emit task end
Testing: starting task with name: 17
Testing: find_taskcode NOT YET SPECIFIED,  17  -->  12
Testing: starting task number 12  name is 17 which is coded into 12 
Testing: emit task start code 12, number 12
Testing: replay_input_task parName 17    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  9  ->   12 (INPUT) 
Testing: emit dependency from the previous task no: 9
Testing: replay_inout_task parName 17  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  9  ->   12 (INOUT) 
Testing: emit dependency from the previous task no: 9
Testing: task: 17
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 6
Testing: ending task 
Testing: ending task number 12
Testing: emit task end
Testing: starting task with name: 18
Testing: find_taskcode NOT YET SPECIFIED,  18  -->  13
Testing: starting task number 13  name is 18 which is coded into 13 
Testing: emit task start code 13, number 13
Testing: replay_output_task parName 18    ptr ,  element_size 4,   elements  1      
Testing: replay_output_task parName 18    ptr ,  element_size 4,   elements  1      
Testing: replay_inout_task parName 18  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  12  ->   13 (INOUT) 
Testing: emit dependency from the previous task no: 12
Testing: task: 18
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 1
Testing: ending task 
Testing: ending task number 13
Testing: emit task end
Testing: starting task with name: 19
Testing: find_taskcode NOT YET SPECIFIED,  19  -->  14
Testing: starting task number 14  name is 19 which is coded into 14 
Testing: emit task start code 14, number 14
Testing: replay_inout_task parName 19  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  13  ->   14 (INOUT) 
Testing: emit dependency from the previous task no: 13
Testing: replay_inout_task parName 19  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  13  ->   14 (INOUT) 
Testing: emit dependency from the previous task no: 13
Testing: task: 19
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 2
Testing: ending task 
Testing: ending task number 14
Testing: emit task end
Testing: starting task with name: 20
Testing: find_taskcode NOT YET SPECIFIED,  20  -->  15
Testing: starting task number 15  name is 20 which is coded into 15 
Testing: emit task start code 15, number 15
Testing: replay_output_task parName 20    ptr ,  element_size 4,   elements  1      
Testing: replay_output_task parName 20    ptr ,  element_size 4,   elements  1      
Testing: replay_inout_task parName 20  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  14  ->   15 (INOUT) 
Testing: emit dependency from the previous task no: 14
Testing: replay_inout_task parName 20  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  14  ->   15 (INOUT) 
Testing: emit dependency from the previous task no: 14
Testing: task: 20
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 3
Testing: ending task 
Testing: ending task number 15
Testing: emit task end
Testing: starting task with name: 21
Testing: find_taskcode NOT YET SPECIFIED,  21  -->  16
Testing: starting task number 16  name is 21 which is coded into 16 
Testing: emit task start code 16, number 16
Testing: replay_input_task parName 21    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  15  ->   16 (INPUT) 
Testing: emit dependency from the previous task no: 15
Testing: task: 21
Testing: Testing: Testing: Testing: Testing: Testing: Done task 4
Testing: ending task 
Testing: ending task number 16
Testing: emit task end
Testing: starting task with name: 22
Testing: find_taskcode NOT YET SPECIFIED,  22  -->  17
Testing: starting task number 17  name is 22 which is coded into 17 
Testing: emit task start code 17, number 17
Testing: replay_input_task parName 22    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  15  ->   17 (INPUT) 
Testing: emit dependency from the previous task no: 15
Testing: task: 22
Testing: Testing: Testing: Testing: Testing: Testing: Done task 5
Testing: ending task 
Testing: ending task number 17
Testing: emit task end
Testing: starting task with name: 23
Testing: find_taskcode NOT YET SPECIFIED,  23  -->  18
Testing: starting task number 18  name is 23 which is coded into 18 
Testing: emit task start code 18, number 18
Testing: replay_input_task parName 23    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  15  ->   18 (INPUT) 
Testing: emit dependency from the previous task no: 15
Testing: replay_inout_task parName 23  ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  15  ->   18 (INOUT) 
Testing: emit dependency from the previous task no: 15
Testing: task: 23
Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Testing: Done task 6
Testing: ending task 
Testing: ending task number 18
Testing: emit task end
Extrae: Intermediate raw trace file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in_out1/set-0/TRACE.0000017879000000000000.mpit
Extrae: Intermediate raw sym file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in_out1/set-0/TRACE.0000017879000000000000.sym
Extrae: Deallocating memory.
Extrae: Application has ended. Tracing has been terminated.
Extrae: Proceeding with the merge of the intermediate tracefiles.
Extrae: Executing the merge process (using /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in_out1/TRACE.mpits).
merger: Extrae 3.1.0 (revision 3316 based on extrae/trunk)
mpi2prv: Assigned nodes < bsc-Latitude-E7440 >
mpi2prv: Assigned size per processor < <1 Mbyte >
mpi2prv: File /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in_out1/set-0/TRACE.0000017879000000000000.mpit is object 1.1.1 on node bsc-Latitude-E7440 assigned to processor 0
mpi2prv: Time synchronization has been turned off
mpi2prv: Checking for target directory existance... exists, ok!
mpi2prv: Ignoring symbols from the application execution because mpi2prv does not support BFD
mpi2prv: Selected output trace format is Paraver
mpi2prv: Stored trace format is Paraver
mpi2prv: Searching synchronization points... done
mpi2prv: Enabling Time Synchronization (Node).
mpi2prv: Circular buffer enabled at tracing time? NO
mpi2prv: Parsing intermediate files
mpi2prv: Progress 1 of 2 ... 5.3% 10.6% 15.0% 20.4% 25.7% 30.1% 35.4% 40.7% 45.1% 50.4% 55.8% 60.2% 65.5% 70.8% 75.2% 80.5% 85.8% 90.3% 95.6% done
mpi2prv: Processor 0 succeeded to translate its assigned files
mpi2prv: Elapsed time translating files: 0 hours 0 minutes 0 seconds
mpi2prv: Elapsed time sorting addresses: 0 hours 0 minutes 0 seconds
mpi2prv: Generating tracefile (intermediate buffers of 6710784 events)
         This process can take a while. Please, be patient.
mpi2prv: Progress 2 of 2 ... 9.0% 11.5% 15.6% 20.5% 25.4% 30.3% 35.2% 40.2% 45.1% 50.8% 55.7% 60.7% 65.6% 70.5% 75.4% 80.3% 85.2% 90.2% 95.9% done
mpi2prv: Elapsed time merge step: 0 hours 0 minutes 0 seconds
mpi2prv: Resulting tracefile occupies 3027 bytes
mpi2prv: Removing temporal files... done
mpi2prv: Elapsed time removing temporal files: 0 hours 0 minutes 0 seconds
mpi2prv: Congratulations! EXTRAE_Paraver_trace.prv has been generated.
