Welcome to Extrae 3.1.0 (revision 3316 based on extrae/trunk)
Extrae: Parsing the configuration file (../extrae.xml) begins
Extrae: Tracing package is located on /scratch/package
Extrae: Generating intermediate files for Paraver traces.
Extrae: Tracing buffer can hold 500000 events
Extrae: Circular buffer disabled.
Extrae: Dynamic memory instrumentation is disabled.
Extrae: Basic I/O memory instrumentation is disabled.
Extrae: Parsing the configuration file (../extrae.xml) has ended
Extrae: Intermediate traces will be stored in /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commcon1
Extrae: Tracing mode is set to: Detail.
Extrae: Successfully initiated with 1 tasks

starting program
Warning: not specified file with names of the tasks: use export TASKNAMES=<path>
The names of the tasks may be corrupted!!!!
Testing: emit css start 
Testing: starting task with name: 6
Testing: find_taskcode NOT YET SPECIFIED,  6  -->  1
Testing: starting task number 1  name is 6 which is coded into 1 
Testing: emit task start code 1, number 1
Testing: replay_concurrent_task parName 6  ptr ,  element_size 40000,   elements  1      
Testing: emit concurrent task start with mapped address 0
Testing: task: 6
finish some_work_concurrent, values from 0 to 999
Testing: ending task with name: 6
Testing: emit concurrent task end with mapped address 0
Testing: ending task number 1
Testing: emit task end
Testing: starting task with name: 7
Testing: find_taskcode NOT YET SPECIFIED,  7  -->  2
Testing: starting task number 2  name is 7 which is coded into 2 
Testing: emit task start code 2, number 2
Testing: replay_concurrent_task parName 7  ptr ,  element_size 40000,   elements  1      
Testing: emit concurrent task start with mapped address 0
Testing: task: 7
finish some_work_concurrent, values from 10000 to 10999
Testing: ending task with name: 7
Testing: emit concurrent task end with mapped address 0
Testing: ending task number 2
Testing: emit task end
Testing: starting task with name: 8
Testing: find_taskcode NOT YET SPECIFIED,  8  -->  3
Testing: starting task number 3  name is 8 which is coded into 3 
Testing: emit task start code 3, number 3
Testing: replay_commutative_task parName 8  ptr ,  element_size 40000,   elements  1      
Testing: emit commutative task start with mapped address 0
Testing: there is dependency tasks:  1  ->   3 (INOUT) 
Testing: there is dependency tasks:  2  ->   3 (INOUT) 
Testing: emit dependency from the previous task no: 1
Testing: emit dependency from the previous task no: 2
Testing: task: 8
finish some_work_commutative, values from 0 to 999
Testing: ending task with name: 8
Testing: emit commutative task end with mapped address 0
Testing: ending task number 3
Testing: emit task end
Testing: starting task with name: 9
Testing: find_taskcode NOT YET SPECIFIED,  9  -->  4
Testing: starting task number 4  name is 9 which is coded into 4 
Testing: emit task start code 4, number 4
Testing: replay_commutative_task parName 9  ptr ,  element_size 40000,   elements  1      
Testing: emit commutative task start with mapped address 0
Testing: there is dependency tasks:  1  ->   4 (INOUT) 
Testing: there is dependency tasks:  2  ->   4 (INOUT) 
Testing: emit dependency from the previous task no: 1
Testing: emit dependency from the previous task no: 2
Testing: task: 9
finish some_work_commutative, values from 10000 to 10999
Testing: ending task with name: 9
Testing: emit commutative task end with mapped address 0
Testing: ending task number 4
Testing: emit task end
Testing: starting task with name: 10
Testing: find_taskcode NOT YET SPECIFIED,  10  -->  5
Testing: starting task number 5  name is 10 which is coded into 5 
Testing: emit task start code 5, number 5
Testing: replay_inout_task parName 10  ptr ,  element_size 40000,   elements  1      
Testing: there is dependency tasks:  3  ->   5 (INOUT) 
Testing: there is dependency tasks:  4  ->   5 (INOUT) 
Testing: emit dependency from the previous task no: 3
Testing: emit dependency from the previous task no: 4
Testing: task: 10
finish some_work_inout
Testing: ending task with name: 10
Testing: ending task number 5
Testing: emit task end
Testing: starting task with name: 11
Testing: find_taskcode NOT YET SPECIFIED,  11  -->  6
Testing: starting task number 6  name is 11 which is coded into 6 
Testing: emit task start code 6, number 6
Testing: replay_commutative_task parName 11  ptr ,  element_size 40000,   elements  1      
Testing: emit commutative task start with mapped address 1
Testing: task: 11
finish some_work_commutative, values from 0 to 999
Testing: ending task with name: 11
Testing: emit commutative task end with mapped address 1
Testing: ending task number 6
Testing: emit task end
Testing: starting task with name: 12
Testing: find_taskcode NOT YET SPECIFIED,  12  -->  7
Testing: starting task number 7  name is 12 which is coded into 7 
Testing: emit task start code 7, number 7
Testing: replay_commutative_task parName 12  ptr ,  element_size 40000,   elements  1      
Testing: emit commutative task start with mapped address 1
Testing: task: 12
finish some_work_commutative, values from 10000 to 10999
Testing: ending task with name: 12
Testing: emit commutative task end with mapped address 1
Testing: ending task number 7
Testing: emit task end
Testing: starting task with name: 13
Testing: find_taskcode NOT YET SPECIFIED,  13  -->  8
Testing: starting task number 8  name is 13 which is coded into 8 
Testing: emit task start code 8, number 8
Testing: replay_concurrent_task parName 13  ptr ,  element_size 40000,   elements  1      
Testing: emit concurrent task start with mapped address 1
Testing: there is dependency tasks:  6  ->   8 (INOUT) 
Testing: there is dependency tasks:  7  ->   8 (INOUT) 
Testing: emit dependency from the previous task no: 6
Testing: emit dependency from the previous task no: 7
Testing: task: 13
finish some_work_concurrent, values from 0 to 999
Testing: ending task with name: 13
Testing: emit concurrent task end with mapped address 1
Testing: ending task number 8
Testing: emit task end
Testing: starting task with name: 14
Testing: find_taskcode NOT YET SPECIFIED,  14  -->  9
Testing: starting task number 9  name is 14 which is coded into 9 
Testing: emit task start code 9, number 9
Testing: replay_concurrent_task parName 14  ptr ,  element_size 40000,   elements  1      
Testing: emit concurrent task start with mapped address 1
Testing: there is dependency tasks:  6  ->   9 (INOUT) 
Testing: there is dependency tasks:  7  ->   9 (INOUT) 
Testing: emit dependency from the previous task no: 6
Testing: emit dependency from the previous task no: 7
Testing: task: 14
finish some_work_concurrent, values from 10000 to 10999
Testing: ending task with name: 14
Testing: emit concurrent task end with mapped address 1
Testing: ending task number 9
Testing: emit task end
Testing: starting task with name: 15
Testing: find_taskcode NOT YET SPECIFIED,  15  -->  10
Testing: starting task number 10  name is 15 which is coded into 10 
Testing: emit task start code 10, number 10
Testing: replay_inout_task parName 15  ptr ,  element_size 40000,   elements  1      
Testing: there is dependency tasks:  8  ->   10 (INOUT) 
Testing: there is dependency tasks:  9  ->   10 (INOUT) 
Testing: emit dependency from the previous task no: 8
Testing: emit dependency from the previous task no: 9
Testing: task: 15
finish some_work_inout
Testing: ending task with name: 15
Testing: ending task number 10
Testing: emit task end
program end
Extrae: Intermediate raw trace file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commcon1/set-0/TRACE.0000019618000000000000.mpit
Extrae: Intermediate raw sym file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commcon1/set-0/TRACE.0000019618000000000000.sym
Extrae: Deallocating memory.
Extrae: Application has ended. Tracing has been terminated.
Extrae: Proceeding with the merge of the intermediate tracefiles.
Extrae: Executing the merge process (using /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commcon1/TRACE.mpits).
merger: Extrae 3.1.0 (revision 3316 based on extrae/trunk)
mpi2prv: Assigned nodes < bsc-Latitude-E7440 >
mpi2prv: Assigned size per processor < <1 Mbyte >
mpi2prv: File /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commcon1/set-0/TRACE.0000019618000000000000.mpit is object 1.1.1 on node bsc-Latitude-E7440 assigned to processor 0
mpi2prv: Time synchronization has been turned off
mpi2prv: Checking for target directory existance... exists, ok!
mpi2prv: Ignoring symbols from the application execution because mpi2prv does not support BFD
mpi2prv: Selected output trace format is Paraver
mpi2prv: Stored trace format is Paraver
mpi2prv: Searching synchronization points... done
mpi2prv: Enabling Time Synchronization (Node).
mpi2prv: Circular buffer enabled at tracing time? NO
mpi2prv: Parsing intermediate files
mpi2prv: Progress 1 of 2 ... 6.0% 10.8% 15.7% 20.5% 25.3% 30.1% 36.1% 41.0% 45.8% 50.6% 55.4% 60.2% 65.1% 71.1% 75.9% 80.7% 85.5% 90.4% 95.2% done
mpi2prv: Processor 0 succeeded to translate its assigned files
mpi2prv: Elapsed time translating files: 0 hours 0 minutes 0 seconds
mpi2prv: Elapsed time sorting addresses: 0 hours 0 minutes 0 seconds
mpi2prv: Generating tracefile (intermediate buffers of 6710784 events)
         This process can take a while. Please, be patient.
mpi2prv: Progress 2 of 2 ... 5.4% 12.0% 15.2% 20.7% 26.1% 30.4% 35.9% 40.2% 45.7% 51.1% 55.4% 60.9% 65.2% 70.7% 76.1% 80.4% 85.9% 90.2% 95.7% done
mpi2prv: Elapsed time merge step: 0 hours 0 minutes 0 seconds
mpi2prv: Resulting tracefile occupies 2220 bytes
mpi2prv: Removing temporal files... done
mpi2prv: Elapsed time removing temporal files: 0 hours 0 minutes 0 seconds
mpi2prv: Congratulations! EXTRAE_Paraver_trace.prv has been generated.
