Welcome to Extrae 3.1.0 (revision 3316 based on extrae/trunk)
Extrae: Parsing the configuration file (../extrae.xml) begins
Extrae: Tracing package is located on /scratch/package
Extrae: Generating intermediate files for Paraver traces.
Extrae: Tracing buffer can hold 500000 events
Extrae: Circular buffer disabled.
Extrae: Dynamic memory instrumentation is disabled.
Extrae: Basic I/O memory instrumentation is disabled.
Extrae: Parsing the configuration file (../extrae.xml) has ended
Extrae: Intermediate traces will be stored in /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_interc_in_out
Extrae: Tracing mode is set to: Detail.
Extrae: Successfully initiated with 1 tasks

starting program
Warning: not specified file with names of the tasks: use export TASKNAMES=<path>
The names of the tasks may be corrupted!!!!
Testing: emit css start 
Testing: starting task with name: 6
Testing: find_taskcode NOT YET SPECIFIED,  6  -->  1
Testing: starting task number 1  name is 6 which is coded into 1 
Testing: emit task start code 1, number 1
Testing: replay_output_task parName 6    ptr ,  element_size 4,   elements  1      
Testing: task: 6
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 1
Testing: emit task end
Testing: starting task with name: 7
Testing: find_taskcode NOT YET SPECIFIED,  7  -->  2
Testing: starting task number 2  name is 7 which is coded into 2 
Testing: emit task start code 2, number 2
Testing: replay_input_task parName 7    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  1  ->   2 (INPUT) 
Testing: emit dependency from the previous task no: 1
Testing: task: 7
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 2
Testing: emit task end
Testing: starting task with name: 8
Testing: find_taskcode NOT YET SPECIFIED,  8  -->  3
Testing: starting task number 3  name is 8 which is coded into 3 
Testing: emit task start code 3, number 3
Testing: replay_output_task parName 8    ptr ,  element_size 4,   elements  1      
Testing: task: 8
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 3
Testing: emit task end
Testing: starting task with name: 9
Testing: find_taskcode NOT YET SPECIFIED,  9  -->  4
Testing: starting task number 4  name is 9 which is coded into 4 
Testing: emit task start code 4, number 4
Testing: replay_input_task parName 9    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  3  ->   4 (INPUT) 
Testing: emit dependency from the previous task no: 3
Testing: task: 9
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 4
Testing: emit task end
Testing: starting task with name: 10
Testing: find_taskcode NOT YET SPECIFIED,  10  -->  5
Testing: starting task number 5  name is 10 which is coded into 5 
Testing: emit task start code 5, number 5
Testing: replay_output_task parName 10    ptr ,  element_size 4,   elements  1      
Testing: task: 10
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 5
Testing: emit task end
Testing: starting task with name: 11
Testing: find_taskcode NOT YET SPECIFIED,  11  -->  6
Testing: starting task number 6  name is 11 which is coded into 6 
Testing: emit task start code 6, number 6
Testing: replay_input_task parName 11    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  5  ->   6 (INPUT) 
Testing: emit dependency from the previous task no: 5
Testing: task: 11
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 6
Testing: emit task end
Testing: starting task with name: 12
Testing: find_taskcode NOT YET SPECIFIED,  12  -->  7
Testing: starting task number 7  name is 12 which is coded into 7 
Testing: emit task start code 7, number 7
Testing: replay_output_task parName 12    ptr ,  element_size 4,   elements  1      
Testing: task: 12
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 7
Testing: emit task end
Testing: starting task with name: 13
Testing: find_taskcode NOT YET SPECIFIED,  13  -->  8
Testing: starting task number 8  name is 13 which is coded into 8 
Testing: emit task start code 8, number 8
Testing: replay_input_task parName 13    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  7  ->   8 (INPUT) 
Testing: emit dependency from the previous task no: 7
Testing: task: 13
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 8
Testing: emit task end
Testing: starting task with name: 14
Testing: find_taskcode NOT YET SPECIFIED,  14  -->  9
Testing: starting task number 9  name is 14 which is coded into 9 
Testing: emit task start code 9, number 9
Testing: replay_output_task parName 14    ptr ,  element_size 4,   elements  1      
Testing: task: 14
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 9
Testing: emit task end
Testing: starting task with name: 15
Testing: find_taskcode NOT YET SPECIFIED,  15  -->  10
Testing: starting task number 10  name is 15 which is coded into 10 
Testing: emit task start code 10, number 10
Testing: replay_input_task parName 15    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  9  ->   10 (INPUT) 
Testing: emit dependency from the previous task no: 9
Testing: task: 15
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 10
Testing: emit task end
Testing: starting task with name: 16
Testing: find_taskcode NOT YET SPECIFIED,  16  -->  11
Testing: starting task number 11  name is 16 which is coded into 11 
Testing: emit task start code 11, number 11
Testing: replay_output_task parName 16    ptr ,  element_size 4,   elements  1      
Testing: task: 16
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 11
Testing: emit task end
Testing: starting task with name: 17
Testing: find_taskcode NOT YET SPECIFIED,  17  -->  12
Testing: starting task number 12  name is 17 which is coded into 12 
Testing: emit task start code 12, number 12
Testing: replay_input_task parName 17    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  11  ->   12 (INPUT) 
Testing: emit dependency from the previous task no: 11
Testing: task: 17
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 12
Testing: emit task end
Testing: starting task with name: 18
Testing: find_taskcode NOT YET SPECIFIED,  18  -->  13
Testing: starting task number 13  name is 18 which is coded into 13 
Testing: emit task start code 13, number 13
Testing: replay_output_task parName 18    ptr ,  element_size 4,   elements  1      
Testing: task: 18
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 13
Testing: emit task end
Testing: starting task with name: 19
Testing: find_taskcode NOT YET SPECIFIED,  19  -->  14
Testing: starting task number 14  name is 19 which is coded into 14 
Testing: emit task start code 14, number 14
Testing: replay_input_task parName 19    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  13  ->   14 (INPUT) 
Testing: emit dependency from the previous task no: 13
Testing: task: 19
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 14
Testing: emit task end
Testing: starting task with name: 20
Testing: find_taskcode NOT YET SPECIFIED,  20  -->  15
Testing: starting task number 15  name is 20 which is coded into 15 
Testing: emit task start code 15, number 15
Testing: replay_output_task parName 20    ptr ,  element_size 4,   elements  1      
Testing: task: 20
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 15
Testing: emit task end
Testing: starting task with name: 21
Testing: find_taskcode NOT YET SPECIFIED,  21  -->  16
Testing: starting task number 16  name is 21 which is coded into 16 
Testing: emit task start code 16, number 16
Testing: replay_input_task parName 21    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  15  ->   16 (INPUT) 
Testing: emit dependency from the previous task no: 15
Testing: task: 21
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 16
Testing: emit task end
Testing: starting task with name: 22
Testing: find_taskcode NOT YET SPECIFIED,  22  -->  17
Testing: starting task number 17  name is 22 which is coded into 17 
Testing: emit task start code 17, number 17
Testing: replay_output_task parName 22    ptr ,  element_size 4,   elements  1      
Testing: task: 22
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 17
Testing: emit task end
Testing: starting task with name: 23
Testing: find_taskcode NOT YET SPECIFIED,  23  -->  18
Testing: starting task number 18  name is 23 which is coded into 18 
Testing: emit task start code 18, number 18
Testing: replay_input_task parName 23    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  17  ->   18 (INPUT) 
Testing: emit dependency from the previous task no: 17
Testing: task: 23
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 18
Testing: emit task end
Testing: starting task with name: 24
Testing: find_taskcode NOT YET SPECIFIED,  24  -->  19
Testing: starting task number 19  name is 24 which is coded into 19 
Testing: emit task start code 19, number 19
Testing: replay_output_task parName 24    ptr ,  element_size 4,   elements  1      
Testing: task: 24
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 19
Testing: emit task end
Testing: starting task with name: 25
Testing: find_taskcode NOT YET SPECIFIED,  25  -->  20
Testing: starting task number 20  name is 25 which is coded into 20 
Testing: emit task start code 20, number 20
Testing: replay_input_task parName 25    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  19  ->   20 (INPUT) 
Testing: emit dependency from the previous task no: 19
Testing: task: 25
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 20
Testing: emit task end
Testing: starting task with name: 26
Testing: find_taskcode NOT YET SPECIFIED,  26  -->  21
Testing: starting task number 21  name is 26 which is coded into 21 
Testing: emit task start code 21, number 21
Testing: replay_output_task parName 26    ptr ,  element_size 4,   elements  1      
Testing: task: 26
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 21
Testing: emit task end
Testing: starting task with name: 27
Testing: find_taskcode NOT YET SPECIFIED,  27  -->  22
Testing: starting task number 22  name is 27 which is coded into 22 
Testing: emit task start code 22, number 22
Testing: replay_output_task parName 27    ptr ,  element_size 4,   elements  1      
Testing: task: 27
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 22
Testing: emit task end
Testing: starting task with name: 28
Testing: find_taskcode NOT YET SPECIFIED,  28  -->  23
Testing: starting task number 23  name is 28 which is coded into 23 
Testing: emit task start code 23, number 23
Testing: replay_output_task parName 28    ptr ,  element_size 4,   elements  1      
Testing: task: 28
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 23
Testing: emit task end
Testing: starting task with name: 29
Testing: find_taskcode NOT YET SPECIFIED,  29  -->  24
Testing: starting task number 24  name is 29 which is coded into 24 
Testing: emit task start code 24, number 24
Testing: replay_output_task parName 29    ptr ,  element_size 4,   elements  1      
Testing: task: 29
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 24
Testing: emit task end
Testing: starting task with name: 30
Testing: find_taskcode NOT YET SPECIFIED,  30  -->  25
Testing: starting task number 25  name is 30 which is coded into 25 
Testing: emit task start code 25, number 25
Testing: replay_output_task parName 30    ptr ,  element_size 4,   elements  1      
Testing: task: 30
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 25
Testing: emit task end
Testing: starting task with name: 31
Testing: find_taskcode NOT YET SPECIFIED,  31  -->  26
Testing: starting task number 26  name is 31 which is coded into 26 
Testing: emit task start code 26, number 26
Testing: replay_output_task parName 31    ptr ,  element_size 4,   elements  1      
Testing: task: 31
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 26
Testing: emit task end
Testing: starting task with name: 32
Testing: find_taskcode NOT YET SPECIFIED,  32  -->  27
Testing: starting task number 27  name is 32 which is coded into 27 
Testing: emit task start code 27, number 27
Testing: replay_output_task parName 32    ptr ,  element_size 4,   elements  1      
Testing: task: 32
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 27
Testing: emit task end
Testing: starting task with name: 33
Testing: find_taskcode NOT YET SPECIFIED,  33  -->  28
Testing: starting task number 28  name is 33 which is coded into 28 
Testing: emit task start code 28, number 28
Testing: replay_output_task parName 33    ptr ,  element_size 4,   elements  1      
Testing: task: 33
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 28
Testing: emit task end
Testing: starting task with name: 34
Testing: find_taskcode NOT YET SPECIFIED,  34  -->  29
Testing: starting task number 29  name is 34 which is coded into 29 
Testing: emit task start code 29, number 29
Testing: replay_output_task parName 34    ptr ,  element_size 4,   elements  1      
Testing: task: 34
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 29
Testing: emit task end
Testing: starting task with name: 35
Testing: find_taskcode NOT YET SPECIFIED,  35  -->  30
Testing: starting task number 30  name is 35 which is coded into 30 
Testing: emit task start code 30, number 30
Testing: replay_output_task parName 35    ptr ,  element_size 4,   elements  1      
Testing: task: 35
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 30
Testing: emit task end
Testing: starting task with name: 36
Testing: find_taskcode NOT YET SPECIFIED,  36  -->  31
Testing: starting task number 31  name is 36 which is coded into 31 
Testing: emit task start code 31, number 31
Testing: replay_output_task parName 36    ptr ,  element_size 4,   elements  1      
Testing: task: 36
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 31
Testing: emit task end
Testing: starting task with name: 37
Testing: find_taskcode NOT YET SPECIFIED,  37  -->  32
Testing: starting task number 32  name is 37 which is coded into 32 
Testing: emit task start code 32, number 32
Testing: replay_output_task parName 37    ptr ,  element_size 4,   elements  1      
Testing: task: 37
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 32
Testing: emit task end
Testing: starting task with name: 38
Testing: find_taskcode NOT YET SPECIFIED,  38  -->  33
Testing: starting task number 33  name is 38 which is coded into 33 
Testing: emit task start code 33, number 33
Testing: replay_output_task parName 38    ptr ,  element_size 4,   elements  1      
Testing: task: 38
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 33
Testing: emit task end
Testing: starting task with name: 39
Testing: find_taskcode NOT YET SPECIFIED,  39  -->  34
Testing: starting task number 34  name is 39 which is coded into 34 
Testing: emit task start code 34, number 34
Testing: replay_output_task parName 39    ptr ,  element_size 4,   elements  1      
Testing: task: 39
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 34
Testing: emit task end
Testing: starting task with name: 40
Testing: find_taskcode NOT YET SPECIFIED,  40  -->  35
Testing: starting task number 35  name is 40 which is coded into 35 
Testing: emit task start code 35, number 35
Testing: replay_output_task parName 40    ptr ,  element_size 4,   elements  1      
Testing: task: 40
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 35
Testing: emit task end
Testing: starting task with name: 41
Testing: find_taskcode NOT YET SPECIFIED,  41  -->  36
Testing: starting task number 36  name is 41 which is coded into 36 
Testing: emit task start code 36, number 36
Testing: replay_output_task parName 41    ptr ,  element_size 4,   elements  1      
Testing: task: 41
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 36
Testing: emit task end
Testing: starting task with name: 42
Testing: find_taskcode NOT YET SPECIFIED,  42  -->  37
Testing: starting task number 37  name is 42 which is coded into 37 
Testing: emit task start code 37, number 37
Testing: replay_output_task parName 42    ptr ,  element_size 4,   elements  1      
Testing: task: 42
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 37
Testing: emit task end
Testing: starting task with name: 43
Testing: find_taskcode NOT YET SPECIFIED,  43  -->  38
Testing: starting task number 38  name is 43 which is coded into 38 
Testing: emit task start code 38, number 38
Testing: replay_output_task parName 43    ptr ,  element_size 4,   elements  1      
Testing: task: 43
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 38
Testing: emit task end
Testing: starting task with name: 44
Testing: find_taskcode NOT YET SPECIFIED,  44  -->  39
Testing: starting task number 39  name is 44 which is coded into 39 
Testing: emit task start code 39, number 39
Testing: replay_output_task parName 44    ptr ,  element_size 4,   elements  1      
Testing: task: 44
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 39
Testing: emit task end
Testing: starting task with name: 45
Testing: find_taskcode NOT YET SPECIFIED,  45  -->  40
Testing: starting task number 40  name is 45 which is coded into 40 
Testing: emit task start code 40, number 40
Testing: replay_output_task parName 45    ptr ,  element_size 4,   elements  1      
Testing: task: 45
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 40
Testing: emit task end
Testing: starting task with name: 46
Testing: find_taskcode NOT YET SPECIFIED,  46  -->  41
Testing: starting task number 41  name is 46 which is coded into 41 
Testing: emit task start code 41, number 41
Testing: replay_input_task parName 46    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   41 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 46
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 41
Testing: emit task end
Testing: starting task with name: 47
Testing: find_taskcode NOT YET SPECIFIED,  47  -->  42
Testing: starting task number 42  name is 47 which is coded into 42 
Testing: emit task start code 42, number 42
Testing: replay_input_task parName 47    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   42 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 47
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 42
Testing: emit task end
Testing: starting task with name: 48
Testing: find_taskcode NOT YET SPECIFIED,  48  -->  43
Testing: starting task number 43  name is 48 which is coded into 43 
Testing: emit task start code 43, number 43
Testing: replay_input_task parName 48    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   43 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 48
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 43
Testing: emit task end
Testing: starting task with name: 49
Testing: find_taskcode NOT YET SPECIFIED,  49  -->  44
Testing: starting task number 44  name is 49 which is coded into 44 
Testing: emit task start code 44, number 44
Testing: replay_input_task parName 49    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   44 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 49
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 44
Testing: emit task end
Testing: starting task with name: 50
Testing: find_taskcode NOT YET SPECIFIED,  50  -->  45
Testing: starting task number 45  name is 50 which is coded into 45 
Testing: emit task start code 45, number 45
Testing: replay_input_task parName 50    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   45 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 50
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 45
Testing: emit task end
Testing: starting task with name: 51
Testing: find_taskcode NOT YET SPECIFIED,  51  -->  46
Testing: starting task number 46  name is 51 which is coded into 46 
Testing: emit task start code 46, number 46
Testing: replay_input_task parName 51    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   46 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 51
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 46
Testing: emit task end
Testing: starting task with name: 52
Testing: find_taskcode NOT YET SPECIFIED,  52  -->  47
Testing: starting task number 47  name is 52 which is coded into 47 
Testing: emit task start code 47, number 47
Testing: replay_input_task parName 52    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   47 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 52
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 47
Testing: emit task end
Testing: starting task with name: 53
Testing: find_taskcode NOT YET SPECIFIED,  53  -->  48
Testing: starting task number 48  name is 53 which is coded into 48 
Testing: emit task start code 48, number 48
Testing: replay_input_task parName 53    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   48 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 53
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 48
Testing: emit task end
Testing: starting task with name: 54
Testing: find_taskcode NOT YET SPECIFIED,  54  -->  49
Testing: starting task number 49  name is 54 which is coded into 49 
Testing: emit task start code 49, number 49
Testing: replay_input_task parName 54    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   49 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 54
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 49
Testing: emit task end
Testing: starting task with name: 55
Testing: find_taskcode NOT YET SPECIFIED,  55  -->  50
Testing: starting task number 50  name is 55 which is coded into 50 
Testing: emit task start code 50, number 50
Testing: replay_input_task parName 55    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   50 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 55
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 50
Testing: emit task end
Testing: starting task with name: 56
Testing: find_taskcode NOT YET SPECIFIED,  56  -->  51
Testing: starting task number 51  name is 56 which is coded into 51 
Testing: emit task start code 51, number 51
Testing: replay_input_task parName 56    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   51 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 56
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 51
Testing: emit task end
Testing: starting task with name: 57
Testing: find_taskcode NOT YET SPECIFIED,  57  -->  52
Testing: starting task number 52  name is 57 which is coded into 52 
Testing: emit task start code 52, number 52
Testing: replay_input_task parName 57    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   52 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 57
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 52
Testing: emit task end
Testing: starting task with name: 58
Testing: find_taskcode NOT YET SPECIFIED,  58  -->  53
Testing: starting task number 53  name is 58 which is coded into 53 
Testing: emit task start code 53, number 53
Testing: replay_input_task parName 58    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   53 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 58
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 53
Testing: emit task end
Testing: starting task with name: 59
Testing: find_taskcode NOT YET SPECIFIED,  59  -->  54
Testing: starting task number 54  name is 59 which is coded into 54 
Testing: emit task start code 54, number 54
Testing: replay_input_task parName 59    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   54 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 59
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 54
Testing: emit task end
Testing: starting task with name: 60
Testing: find_taskcode NOT YET SPECIFIED,  60  -->  55
Testing: starting task number 55  name is 60 which is coded into 55 
Testing: emit task start code 55, number 55
Testing: replay_input_task parName 60    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   55 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 60
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 55
Testing: emit task end
Testing: starting task with name: 61
Testing: find_taskcode NOT YET SPECIFIED,  61  -->  56
Testing: starting task number 56  name is 61 which is coded into 56 
Testing: emit task start code 56, number 56
Testing: replay_input_task parName 61    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   56 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 61
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 56
Testing: emit task end
Testing: starting task with name: 62
Testing: find_taskcode NOT YET SPECIFIED,  62  -->  57
Testing: starting task number 57  name is 62 which is coded into 57 
Testing: emit task start code 57, number 57
Testing: replay_input_task parName 62    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   57 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 62
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 57
Testing: emit task end
Testing: starting task with name: 63
Testing: find_taskcode NOT YET SPECIFIED,  63  -->  58
Testing: starting task number 58  name is 63 which is coded into 58 
Testing: emit task start code 58, number 58
Testing: replay_input_task parName 63    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   58 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 63
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 58
Testing: emit task end
Testing: starting task with name: 64
Testing: find_taskcode NOT YET SPECIFIED,  64  -->  59
Testing: starting task number 59  name is 64 which is coded into 59 
Testing: emit task start code 59, number 59
Testing: replay_input_task parName 64    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   59 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 64
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 59
Testing: emit task end
Testing: starting task with name: 65
Testing: find_taskcode NOT YET SPECIFIED,  65  -->  60
Testing: starting task number 60  name is 65 which is coded into 60 
Testing: emit task start code 60, number 60
Testing: replay_input_task parName 65    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   60 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 65
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 60
Testing: emit task end
Testing: starting task with name: 66
Testing: find_taskcode NOT YET SPECIFIED,  66  -->  61
Testing: starting task number 61  name is 66 which is coded into 61 
Testing: emit task start code 61, number 61
Testing: replay_input_task parName 66    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  40  ->   61 (INPUT) 
Testing: emit dependency from the previous task no: 40
Testing: task: 66
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 61
Testing: emit task end
Testing: starting task with name: 67
Testing: find_taskcode NOT YET SPECIFIED,  67  -->  62
Testing: starting task number 62  name is 67 which is coded into 62 
Testing: emit task start code 62, number 62
Testing: replay_output_task parName 67    ptr ,  element_size 4,   elements  1      
Testing: task: 67
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 62
Testing: emit task end
Testing: starting task with name: 68
Testing: find_taskcode NOT YET SPECIFIED,  68  -->  63
Testing: starting task number 63  name is 68 which is coded into 63 
Testing: emit task start code 63, number 63
Testing: replay_input_task parName 68    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  62  ->   63 (INPUT) 
Testing: emit dependency from the previous task no: 62
Testing: task: 68
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 63
Testing: emit task end
Testing: starting task with name: 69
Testing: find_taskcode NOT YET SPECIFIED,  69  -->  64
Testing: starting task number 64  name is 69 which is coded into 64 
Testing: emit task start code 64, number 64
Testing: replay_output_task parName 69    ptr ,  element_size 4,   elements  1      
Testing: task: 69
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 64
Testing: emit task end
Testing: starting task with name: 70
Testing: find_taskcode NOT YET SPECIFIED,  70  -->  65
Testing: starting task number 65  name is 70 which is coded into 65 
Testing: emit task start code 65, number 65
Testing: replay_input_task parName 70    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  64  ->   65 (INPUT) 
Testing: emit dependency from the previous task no: 64
Testing: task: 70
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 65
Testing: emit task end
Testing: starting task with name: 71
Testing: find_taskcode NOT YET SPECIFIED,  71  -->  66
Testing: starting task number 66  name is 71 which is coded into 66 
Testing: emit task start code 66, number 66
Testing: replay_output_task parName 71    ptr ,  element_size 4,   elements  1      
Testing: task: 71
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 66
Testing: emit task end
Testing: starting task with name: 72
Testing: find_taskcode NOT YET SPECIFIED,  72  -->  67
Testing: starting task number 67  name is 72 which is coded into 67 
Testing: emit task start code 67, number 67
Testing: replay_input_task parName 72    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  66  ->   67 (INPUT) 
Testing: emit dependency from the previous task no: 66
Testing: task: 72
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 67
Testing: emit task end
Testing: starting task with name: 73
Testing: find_taskcode NOT YET SPECIFIED,  73  -->  68
Testing: starting task number 68  name is 73 which is coded into 68 
Testing: emit task start code 68, number 68
Testing: replay_output_task parName 73    ptr ,  element_size 4,   elements  1      
Testing: task: 73
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 68
Testing: emit task end
Testing: starting task with name: 74
Testing: find_taskcode NOT YET SPECIFIED,  74  -->  69
Testing: starting task number 69  name is 74 which is coded into 69 
Testing: emit task start code 69, number 69
Testing: replay_input_task parName 74    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  68  ->   69 (INPUT) 
Testing: emit dependency from the previous task no: 68
Testing: task: 74
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 69
Testing: emit task end
Testing: starting task with name: 75
Testing: find_taskcode NOT YET SPECIFIED,  75  -->  70
Testing: starting task number 70  name is 75 which is coded into 70 
Testing: emit task start code 70, number 70
Testing: replay_output_task parName 75    ptr ,  element_size 4,   elements  1      
Testing: task: 75
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 70
Testing: emit task end
Testing: starting task with name: 76
Testing: find_taskcode NOT YET SPECIFIED,  76  -->  71
Testing: starting task number 71  name is 76 which is coded into 71 
Testing: emit task start code 71, number 71
Testing: replay_input_task parName 76    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  70  ->   71 (INPUT) 
Testing: emit dependency from the previous task no: 70
Testing: task: 76
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 71
Testing: emit task end
Testing: starting task with name: 77
Testing: find_taskcode NOT YET SPECIFIED,  77  -->  72
Testing: starting task number 72  name is 77 which is coded into 72 
Testing: emit task start code 72, number 72
Testing: replay_output_task parName 77    ptr ,  element_size 4,   elements  1      
Testing: task: 77
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 72
Testing: emit task end
Testing: starting task with name: 78
Testing: find_taskcode NOT YET SPECIFIED,  78  -->  73
Testing: starting task number 73  name is 78 which is coded into 73 
Testing: emit task start code 73, number 73
Testing: replay_input_task parName 78    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  72  ->   73 (INPUT) 
Testing: emit dependency from the previous task no: 72
Testing: task: 78
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 73
Testing: emit task end
Testing: starting task with name: 79
Testing: find_taskcode NOT YET SPECIFIED,  79  -->  74
Testing: starting task number 74  name is 79 which is coded into 74 
Testing: emit task start code 74, number 74
Testing: replay_output_task parName 79    ptr ,  element_size 4,   elements  1      
Testing: task: 79
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 74
Testing: emit task end
Testing: starting task with name: 80
Testing: find_taskcode NOT YET SPECIFIED,  80  -->  75
Testing: starting task number 75  name is 80 which is coded into 75 
Testing: emit task start code 75, number 75
Testing: replay_input_task parName 80    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  74  ->   75 (INPUT) 
Testing: emit dependency from the previous task no: 74
Testing: task: 80
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 75
Testing: emit task end
Testing: starting task with name: 81
Testing: find_taskcode NOT YET SPECIFIED,  81  -->  76
Testing: starting task number 76  name is 81 which is coded into 76 
Testing: emit task start code 76, number 76
Testing: replay_output_task parName 81    ptr ,  element_size 4,   elements  1      
Testing: task: 81
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 76
Testing: emit task end
Testing: starting task with name: 82
Testing: find_taskcode NOT YET SPECIFIED,  82  -->  77
Testing: starting task number 77  name is 82 which is coded into 77 
Testing: emit task start code 77, number 77
Testing: replay_input_task parName 82    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  76  ->   77 (INPUT) 
Testing: emit dependency from the previous task no: 76
Testing: task: 82
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 77
Testing: emit task end
Testing: starting task with name: 83
Testing: find_taskcode NOT YET SPECIFIED,  83  -->  78
Testing: starting task number 78  name is 83 which is coded into 78 
Testing: emit task start code 78, number 78
Testing: replay_output_task parName 83    ptr ,  element_size 4,   elements  1      
Testing: task: 83
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 78
Testing: emit task end
Testing: starting task with name: 84
Testing: find_taskcode NOT YET SPECIFIED,  84  -->  79
Testing: starting task number 79  name is 84 which is coded into 79 
Testing: emit task start code 79, number 79
Testing: replay_input_task parName 84    ptr ,  element_size 4,   elements  1      
Testing: there is dependency tasks:  78  ->   79 (INPUT) 
Testing: emit dependency from the previous task no: 78
Testing: task: 84
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 79
Testing: emit task end
Testing: starting task with name: 85
Testing: find_taskcode NOT YET SPECIFIED,  85  -->  80
Testing: starting task number 80  name is 85 which is coded into 80 
Testing: emit task start code 80, number 80
Testing: replay_output_task parName 85    ptr ,  element_size 4,   elements  1      
Testing: task: 85
Testing: Testing: Testing: Testing: Testing: Testing: Done task a
Testing: ending task 
Testing: ending task number 80
Testing: emit task end
Extrae: Intermediate raw trace file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_interc_in_out/set-0/TRACE.0000017861000000000000.mpit
Extrae: Intermediate raw sym file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_interc_in_out/set-0/TRACE.0000017861000000000000.sym
Extrae: Deallocating memory.
Extrae: Application has ended. Tracing has been terminated.
Extrae: Proceeding with the merge of the intermediate tracefiles.
Extrae: Executing the merge process (using /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_interc_in_out/TRACE.mpits).
merger: Extrae 3.1.0 (revision 3316 based on extrae/trunk)
mpi2prv: Assigned nodes < bsc-Latitude-E7440 >
mpi2prv: Assigned size per processor < <1 Mbyte >
mpi2prv: File /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_interc_in_out/set-0/TRACE.0000017861000000000000.mpit is object 1.1.1 on node bsc-Latitude-E7440 assigned to processor 0
mpi2prv: Time synchronization has been turned off
mpi2prv: Checking for target directory existance... exists, ok!
mpi2prv: Ignoring symbols from the application execution because mpi2prv does not support BFD
mpi2prv: Selected output trace format is Paraver
mpi2prv: Stored trace format is Paraver
mpi2prv: Searching synchronization points... done
mpi2prv: Enabling Time Synchronization (Node).
mpi2prv: Circular buffer enabled at tracing time? NO
mpi2prv: Parsing intermediate files
mpi2prv: Progress 1 of 2 ... 5.1% 10.1% 15.2% 20.3% 25.1% 30.1% 35.2% 40.3% 45.1% 50.1% 55.2% 60.3% 65.1% 70.1% 75.2% 80.3% 85.1% 90.1% 95.2% done
mpi2prv: Processor 0 succeeded to translate its assigned files
mpi2prv: Elapsed time translating files: 0 hours 0 minutes 0 seconds
mpi2prv: Elapsed time sorting addresses: 0 hours 0 minutes 0 seconds
mpi2prv: Generating tracefile (intermediate buffers of 6710784 events)
         This process can take a while. Please, be patient.
mpi2prv: Progress 2 of 2 ... 5.2% 10.2% 15.1% 20.1% 25.3% 30.2% 35.2% 40.1% 45.1% 50.3% 55.2% 60.2% 65.1% 70.1% 75.3% 80.2% 85.2% 90.1% 95.1% done
mpi2prv: Elapsed time merge step: 0 hours 0 minutes 0 seconds
mpi2prv: Resulting tracefile occupies 9723 bytes
mpi2prv: Removing temporal files... done
mpi2prv: Elapsed time removing temporal files: 0 hours 0 minutes 0 seconds
mpi2prv: Congratulations! EXTRAE_Paraver_trace.prv has been generated.
