Welcome to Extrae 3.1.0 (revision 3316 based on extrae/trunk)
Extrae: Parsing the configuration file (../extrae.xml) begins
Extrae: Tracing package is located on /scratch/package
Extrae: Generating intermediate files for Paraver traces.
Extrae: Tracing buffer can hold 500000 events
Extrae: Circular buffer disabled.
Extrae: Dynamic memory instrumentation is disabled.
Extrae: Basic I/O memory instrumentation is disabled.
Extrae: Parsing the configuration file (../extrae.xml) has ended
Extrae: Intermediate traces will be stored in /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in
Extrae: Tracing mode is set to: Detail.
Extrae: Successfully initiated with 1 tasks

starting program
Warning: not specified file with names of the tasks: use export TASKNAMES=<path>
The names of the tasks may be corrupted!!!!
Testing: emit css start 
Testing: starting task with name: 6
Testing: find_taskcode NOT YET SPECIFIED,  6  -->  1
Testing: starting task number 1  name is 6 which is coded into 1 
Testing: emit task start code 1, number 1
Testing: replay_input_task parName 6    ptr ,  element_size 4,   elements  1      
Testing: task: 6
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 1
Testing: emit task end
Testing: starting task with name: 7
Testing: find_taskcode NOT YET SPECIFIED,  7  -->  2
Testing: starting task number 2  name is 7 which is coded into 2 
Testing: emit task start code 2, number 2
Testing: replay_input_task parName 7    ptr ,  element_size 4,   elements  1      
Testing: task: 7
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 2
Testing: emit task end
Testing: starting task with name: 8
Testing: find_taskcode NOT YET SPECIFIED,  8  -->  3
Testing: starting task number 3  name is 8 which is coded into 3 
Testing: emit task start code 3, number 3
Testing: replay_input_task parName 8    ptr ,  element_size 4,   elements  1      
Testing: task: 8
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 3
Testing: emit task end
Testing: starting task with name: 9
Testing: find_taskcode NOT YET SPECIFIED,  9  -->  4
Testing: starting task number 4  name is 9 which is coded into 4 
Testing: emit task start code 4, number 4
Testing: replay_input_task parName 9    ptr ,  element_size 4,   elements  1      
Testing: task: 9
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 4
Testing: emit task end
Testing: starting task with name: 10
Testing: find_taskcode NOT YET SPECIFIED,  10  -->  5
Testing: starting task number 5  name is 10 which is coded into 5 
Testing: emit task start code 5, number 5
Testing: replay_input_task parName 10    ptr ,  element_size 4,   elements  1      
Testing: task: 10
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 5
Testing: emit task end
Testing: starting task with name: 11
Testing: find_taskcode NOT YET SPECIFIED,  11  -->  6
Testing: starting task number 6  name is 11 which is coded into 6 
Testing: emit task start code 6, number 6
Testing: replay_input_task parName 11    ptr ,  element_size 4,   elements  1      
Testing: task: 11
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 6
Testing: emit task end
Testing: starting task with name: 12
Testing: find_taskcode NOT YET SPECIFIED,  12  -->  7
Testing: starting task number 7  name is 12 which is coded into 7 
Testing: emit task start code 7, number 7
Testing: replay_input_task parName 12    ptr ,  element_size 4,   elements  1      
Testing: task: 12
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 7
Testing: emit task end
Testing: starting task with name: 13
Testing: find_taskcode NOT YET SPECIFIED,  13  -->  8
Testing: starting task number 8  name is 13 which is coded into 8 
Testing: emit task start code 8, number 8
Testing: replay_input_task parName 13    ptr ,  element_size 4,   elements  1      
Testing: task: 13
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 8
Testing: emit task end
Testing: starting task with name: 14
Testing: find_taskcode NOT YET SPECIFIED,  14  -->  9
Testing: starting task number 9  name is 14 which is coded into 9 
Testing: emit task start code 9, number 9
Testing: replay_input_task parName 14    ptr ,  element_size 4,   elements  1      
Testing: task: 14
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 9
Testing: emit task end
Testing: starting task with name: 15
Testing: find_taskcode NOT YET SPECIFIED,  15  -->  10
Testing: starting task number 10  name is 15 which is coded into 10 
Testing: emit task start code 10, number 10
Testing: replay_input_task parName 15    ptr ,  element_size 4,   elements  1      
Testing: task: 15
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 10
Testing: emit task end
Testing: starting task with name: 16
Testing: find_taskcode NOT YET SPECIFIED,  16  -->  11
Testing: starting task number 11  name is 16 which is coded into 11 
Testing: emit task start code 11, number 11
Testing: replay_input_task parName 16    ptr ,  element_size 4,   elements  1      
Testing: task: 16
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 11
Testing: emit task end
Testing: starting task with name: 17
Testing: find_taskcode NOT YET SPECIFIED,  17  -->  12
Testing: starting task number 12  name is 17 which is coded into 12 
Testing: emit task start code 12, number 12
Testing: replay_input_task parName 17    ptr ,  element_size 4,   elements  1      
Testing: task: 17
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 12
Testing: emit task end
Testing: starting task with name: 18
Testing: find_taskcode NOT YET SPECIFIED,  18  -->  13
Testing: starting task number 13  name is 18 which is coded into 13 
Testing: emit task start code 13, number 13
Testing: replay_input_task parName 18    ptr ,  element_size 4,   elements  1      
Testing: task: 18
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 13
Testing: emit task end
Testing: starting task with name: 19
Testing: find_taskcode NOT YET SPECIFIED,  19  -->  14
Testing: starting task number 14  name is 19 which is coded into 14 
Testing: emit task start code 14, number 14
Testing: replay_input_task parName 19    ptr ,  element_size 4,   elements  1      
Testing: task: 19
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 14
Testing: emit task end
Testing: starting task with name: 20
Testing: find_taskcode NOT YET SPECIFIED,  20  -->  15
Testing: starting task number 15  name is 20 which is coded into 15 
Testing: emit task start code 15, number 15
Testing: replay_input_task parName 20    ptr ,  element_size 4,   elements  1      
Testing: task: 20
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 15
Testing: emit task end
Testing: starting task with name: 21
Testing: find_taskcode NOT YET SPECIFIED,  21  -->  16
Testing: starting task number 16  name is 21 which is coded into 16 
Testing: emit task start code 16, number 16
Testing: replay_input_task parName 21    ptr ,  element_size 4,   elements  1      
Testing: task: 21
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 16
Testing: emit task end
Testing: starting task with name: 22
Testing: find_taskcode NOT YET SPECIFIED,  22  -->  17
Testing: starting task number 17  name is 22 which is coded into 17 
Testing: emit task start code 17, number 17
Testing: replay_input_task parName 22    ptr ,  element_size 4,   elements  1      
Testing: task: 22
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 17
Testing: emit task end
Testing: starting task with name: 23
Testing: find_taskcode NOT YET SPECIFIED,  23  -->  18
Testing: starting task number 18  name is 23 which is coded into 18 
Testing: emit task start code 18, number 18
Testing: replay_input_task parName 23    ptr ,  element_size 4,   elements  1      
Testing: task: 23
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 18
Testing: emit task end
Testing: starting task with name: 24
Testing: find_taskcode NOT YET SPECIFIED,  24  -->  19
Testing: starting task number 19  name is 24 which is coded into 19 
Testing: emit task start code 19, number 19
Testing: replay_input_task parName 24    ptr ,  element_size 4,   elements  1      
Testing: task: 24
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 19
Testing: emit task end
Testing: starting task with name: 25
Testing: find_taskcode NOT YET SPECIFIED,  25  -->  20
Testing: starting task number 20  name is 25 which is coded into 20 
Testing: emit task start code 20, number 20
Testing: replay_input_task parName 25    ptr ,  element_size 4,   elements  1      
Testing: task: 25
Testing: Testing: Testing: Testing: Testing: Testing: Testing: ending task 
Testing: ending task number 20
Testing: emit task end
Extrae: Intermediate raw trace file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in/set-0/TRACE.0000017915000000000000.mpit
Extrae: Intermediate raw sym file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in/set-0/TRACE.0000017915000000000000.sym
Extrae: Deallocating memory.
Extrae: Application has ended. Tracing has been terminated.
Extrae: Proceeding with the merge of the intermediate tracefiles.
Extrae: Executing the merge process (using /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in/TRACE.mpits).
merger: Extrae 3.1.0 (revision 3316 based on extrae/trunk)
mpi2prv: Assigned nodes < bsc-Latitude-E7440 >
mpi2prv: Assigned size per processor < <1 Mbyte >
mpi2prv: File /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_in/set-0/TRACE.0000017915000000000000.mpit is object 1.1.1 on node bsc-Latitude-E7440 assigned to processor 0
mpi2prv: Time synchronization has been turned off
mpi2prv: Checking for target directory existance... exists, ok!
mpi2prv: Ignoring symbols from the application execution because mpi2prv does not support BFD
mpi2prv: Selected output trace format is Paraver
mpi2prv: Stored trace format is Paraver
mpi2prv: Searching synchronization points... done
mpi2prv: Enabling Time Synchronization (Node).
mpi2prv: Circular buffer enabled at tracing time? NO
mpi2prv: Parsing intermediate files
mpi2prv: Progress 1 of 2 ... 5.3% 10.5% 15.8% 21.1% 25.3% 30.5% 35.8% 41.1% 45.3% 50.5% 55.8% 61.1% 65.3% 70.5% 75.8% 81.1% 85.3% 90.5% 95.8% done
mpi2prv: Processor 0 succeeded to translate its assigned files
mpi2prv: Elapsed time translating files: 0 hours 0 minutes 0 seconds
mpi2prv: Elapsed time sorting addresses: 0 hours 0 minutes 0 seconds
mpi2prv: Generating tracefile (intermediate buffers of 6710784 events)
         This process can take a while. Please, be patient.
mpi2prv: Progress 2 of 2 ... 5.8% 10.6% 15.4% 20.2% 26.0% 30.8% 35.6% 40.4% 45.2% 51.0% 55.8% 60.6% 65.4% 70.2% 76.0% 80.8% 85.6% 90.4% 95.2% done
mpi2prv: Elapsed time merge step: 0 hours 0 minutes 0 seconds
mpi2prv: Resulting tracefile occupies 2568 bytes
mpi2prv: Removing temporal files... done
mpi2prv: Elapsed time removing temporal files: 0 hours 0 minutes 0 seconds
mpi2prv: Congratulations! EXTRAE_Paraver_trace.prv has been generated.
