
#ifndef COMMON_H

#define COMMON_EVENT_TYPE_CSS_START          7004
#define COMMON_EVENT_TYPE_PHASEID            7005

#define COMMON_EVENT_TYPE_TASKID             7001
#define COMMON_EVENT_TYPE_TASKNAME_CODED     7003

#define COMMON_EVENT_TYPE_CSS_BARRIER        7006
#define COMMON_EVENT_TYPE_DEPENDENCY         7007

#define COMMON_EVENT_TYPE_CRITICAL_BEGIN     7008
#define COMMON_EVENT_TYPE_CRITICAL_END       7009


#define COMMON_H
#endif