Welcome to Extrae 3.1.0 (revision 3316 based on extrae/trunk)
Extrae: Parsing the configuration file (../extrae.xml) begins
Extrae: Tracing package is located on /scratch/package
Extrae: Generating intermediate files for Paraver traces.
Extrae: Tracing buffer can hold 500000 events
Extrae: Circular buffer disabled.
Extrae: Dynamic memory instrumentation is disabled.
Extrae: Basic I/O memory instrumentation is disabled.
Extrae: Parsing the configuration file (../extrae.xml) has ended
Extrae: Intermediate traces will be stored in /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commutative2
Extrae: Tracing mode is set to: Detail.
Extrae: Successfully initiated with 1 tasks

starting program
Warning: not specified file with names of the tasks: use export TASKNAMES=<path>
The names of the tasks may be corrupted!!!!
Testing: emit css start 
Testing: starting task with name fake_name
Testing: find_taskcode NOT YET SPECIFIED,  fake_name  -->  1
Testing: starting task number 1  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 1
Testing: replay_inout_task parName fake name  ptr ,  element_size 40000,   elements  1      
Testing: task: fake name
Testing: Testing: Testing: Testing: Testing: Testing: finish some work
Testing: ending task 
Testing: ending task number 1
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 2  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 2
Testing: replay_commutative_task parName fake name  ptr ,  element_size 40000,   elements  1      
Testing: there is dependency tasks:  1  ->   2 (INOUT) 
Testing: emit dependency from the previous task no: 1
Testing: task: fake name
Testing: Testing: Testing: Testing: Testing: Testing: finish some work2, values from 0 to 999
Testing: ending task 
Testing: ending task number 2
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 3  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 3
Testing: replay_commutative_task parName fake name  ptr ,  element_size 40000,   elements  1      
Testing: there is dependency tasks:  1  ->   3 (INOUT) 
Testing: emit dependency from the previous task no: 1
Testing: task: fake name
Testing: Testing: Testing: Testing: Testing: Testing: finish some work2, values from 1000 to 1999
Testing: ending task 
Testing: ending task number 3
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 4  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 4
Testing: replay_commutative_task parName fake name  ptr ,  element_size 40000,   elements  1      
Testing: there is dependency tasks:  1  ->   4 (INOUT) 
Testing: emit dependency from the previous task no: 1
Testing: task: fake name
Testing: Testing: Testing: Testing: Testing: Testing: finish some work2, values from 0 to 999
Testing: ending task 
Testing: ending task number 4
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 5  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 5
Testing: replay_commutative_task parName fake name  ptr ,  element_size 40000,   elements  1      
Testing: there is dependency tasks:  1  ->   5 (INOUT) 
Testing: emit dependency from the previous task no: 1
Testing: task: fake name
Testing: Testing: Testing: Testing: Testing: Testing: finish some work2, values from 1000 to 1999
Testing: ending task 
Testing: ending task number 5
Testing: emit task end
Testing: starting task with name fake_name
Testing: find_taskcode ALREADY SPECIFIED,  fake_name  -->  1
Testing: starting task number 6  name is fake_name which is coded into 1 
Testing: emit task start code 1, number 6
Testing: replay_inout_task parName fake name  ptr ,  element_size 40000,   elements  1      
Testing: there is dependency tasks:  2  ->   6 (INOUT) 
Testing: there is dependency tasks:  3  ->   6 (INOUT) 
Testing: there is dependency tasks:  4  ->   6 (INOUT) 
Testing: there is dependency tasks:  5  ->   6 (INOUT) 
Testing: emit dependency from the previous task no: 2
Testing: emit dependency from the previous task no: 3
Testing: emit dependency from the previous task no: 4
Testing: emit dependency from the previous task no: 5
Testing: task: fake name
Testing: Testing: Testing: Testing: Testing: Testing: finish some work
Testing: ending task 
Testing: ending task number 6
Testing: emit task end
program end
Extrae: Intermediate raw trace file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commutative2/set-0/TRACE.0000023090000000000000.mpit
Extrae: Intermediate raw sym file created : /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commutative2/set-0/TRACE.0000023090000000000000.sym
Extrae: Deallocating memory.
Extrae: Application has ended. Tracing has been terminated.
Extrae: Proceeding with the merge of the intermediate tracefiles.
Extrae: Executing the merge process (using /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commutative2/TRACE.mpits).
merger: Extrae 3.1.0 (revision 3316 based on extrae/trunk)
mpi2prv: Assigned nodes < bsc-Latitude-E7440 >
mpi2prv: Assigned size per processor < <1 Mbyte >
mpi2prv: File /home/bsc/bsc/tools/OmpSs_replay/tracing_library/tests/test_commutative2/set-0/TRACE.0000023090000000000000.mpit is object 1.1.1 on node bsc-Latitude-E7440 assigned to processor 0
mpi2prv: Time synchronization has been turned off
mpi2prv: Checking for target directory existance... exists, ok!
mpi2prv: Ignoring symbols from the application execution because mpi2prv does not support BFD
mpi2prv: Selected output trace format is Paraver
mpi2prv: Stored trace format is Paraver
mpi2prv: Searching synchronization points... done
mpi2prv: Enabling Time Synchronization (Node).
mpi2prv: Circular buffer enabled at tracing time? NO
mpi2prv: Parsing intermediate files
mpi2prv: Progress 1 of 2 ... 6.4% 10.6% 17.0% 21.3% 25.5% 31.9% 36.2% 40.4% 46.8% 51.1% 55.3% 61.7% 66.0% 70.2% 76.6% 80.9% 85.1% 91.5% 95.7% done
mpi2prv: Processor 0 succeeded to translate its assigned files
mpi2prv: Elapsed time translating files: 0 hours 0 minutes 0 seconds
mpi2prv: Elapsed time sorting addresses: 0 hours 0 minutes 0 seconds
mpi2prv: Generating tracefile (intermediate buffers of 6710784 events)
         This process can take a while. Please, be patient.
mpi2prv: Progress 2 of 2 ... 5.4% 10.7% 19.6% 21.4% 26.8% 30.4% 35.7% 41.1% 46.4% 51.8% 55.4% 60.7% 66.1% 71.4% 76.8% 80.4% 85.7% 91.1% 96.4% done
mpi2prv: Elapsed time merge step: 0 hours 0 minutes 0 seconds
mpi2prv: Resulting tracefile occupies 1346 bytes
mpi2prv: Removing temporal files... done
mpi2prv: Elapsed time removing temporal files: 0 hours 0 minutes 0 seconds
mpi2prv: Congratulations! EXTRAE_Paraver_trace.prv has been generated.
